// Generated by dia2code
#ifndef CLIENT__EFFECTPACKAGE__H
#define CLIENT__EFFECTPACKAGE__H

#include <string>
#include <unordered_map>
#include <vector>

namespace client {
  class Move;
  class Effect;
}

#include "Move.hpp"
#include "Effect.hpp"

namespace client {

  /// class EffectPackage - 
  class EffectPackage {
    // Attributes
  private:
    std::unordered_map<std::string, Effect> effects;
    // Operations
  public:
    std::vector<std::string> getNames ();
    Move get (std::string name);
    /// exports the package as a JSON string
    std::string jsonExport ();
    void addEffect (std::string name, Effect effect);
    // Setters and Getters
  };

};

#endif
