// Generated by dia2code
#ifndef CLIENT__EFFECT__H
#define CLIENT__EFFECT__H

#include <string>

namespace client {

  /// class Effect - 
  class Effect {
    // Attributes
  private:
    int operation;
    float value;
    bool targetSelf;
    // Operations
  public:
    Effect ();
    void setOperator (int operation);
    void setValue (float value);
    void setTarget (bool self);
    /// returns all fields of the instance in a nicely formatted string for printing to console
    std::string getFormattedStats ();
    /// export the effect as a JSON string
    std::string jsonExport ();
  private:
    std::string getStringOperator ();
    // Setters and Getters
  };

};

#endif
